
server.port=8090

# --- SSL ---
server.ssl.enabled=true
server.ssl.key-store=/tls/keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=${server-ssl-keyStorePassword}

# --- Spring Datasource ---
spring.datasource.url=jdbc:oracle:thin:@//csdbx02dev1e2cz.nhsrx.com:1521/nhindo.pdxinc.com
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=25
spring.datasource.hikari.connection-timeout=120000
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL

# --- Spring JPA ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.open-in-view=false

# --- Logging ---
logging.level.com.rx.ars=DEBUG


# --- Actuator ---
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

# --- Azure Key Vault (used by KeyVaultConfig/KeyVaultComponent) ---
com.rx.ars.azure.key.vault.uri= https://rxn-cs-ars-tm1-kv.vault.azure.net/
com.rx.ars.azure.key.vault.client.id= 624b5b3a-27e4-49f0-bd18-9d67dc659869


# --- OAuth2 / JWT ---
sentinel.issuer-uri=https://idx-stage.linkhealth.com/auth/realms/developer-platform