{{- if and .Values.arsUi.enabled .Values.arsService.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ars-ui.serviceAccountName" . }}
  labels:
    {{- include "ars-ui.labels" . | nindent 4 }}
  {{- with .Values.arsService.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ars-ui.serviceAccountName" . }}
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ars-ui.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "ars-ui.serviceAccountName" . }}
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ include "ars-ui.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
