{{- if .Values.arsUi.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ars-ui-secretproviderclass
spec:
  provider: azure
  secretObjects:

    - secretName: ars-ui-key
      type: Opaque
      data:
        - objectName: server-ssl-keyStorePassword
          key: server-ssl-keyStorePassword

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"

    userAssignedIdentityID: {{ .Values.arsUi.userassignedidentityid }}
    keyvaultName: {{ .Values.arsUi.keyvaultname }}
    tenantId: {{ .Values.arsUi.tenantid }}
    
    syncSecret: "true"

    objects: |
      array:
        - |
          objectName: server-ssl-keyStorePassword
          objectType: secret
  
{{- end }}