{{- if .Values.arsServiceSvc.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ars-service-svc.fullname" . }}
  labels:
    {{- include "ars-service-svc.labels" . | nindent 4 }}
spec:
{{- if not .Values.arsServiceSvc.autoscaling.enabled }}
  replicas: {{ .Values.arsServiceSvc.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "ars-service-svc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
{{- with .Values.arsService.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
{{- end }}
      labels:
        {{- include "ars-service-svc.selectorLabels" . | nindent 8 }}

    spec:
      imagePullSecrets:
        - name: optum-saas-image-pull-secret
      serviceAccountName: {{ include "ars-service-svc.serviceAccountName" . }}

      containers:
        - name: ars-service-svc
          image: "{{ .Values.arsServiceSvc.image.repository }}:{{ .Values.arsServiceSvc.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.arsServiceSvc.image.pullPolicy }}

          # ------------------------------------------------------------------
          # Configuration from ConfigMap and Secrets
          # ------------------------------------------------------------------
          env:
            # Spring active profile

            # Load externalized Spring config from ConfigMap
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:/config/"

            # JVM / Truststore
            - name: JAVA_TOOL_OPTIONS
              value: "-Djavax.net.ssl.trustStore=/tls/truststore.jks -Djavax.net.ssl.trustStoreType=JKS -Dlog4j2.formatMsgNoLookups=true"

            # OAuth issuer
            - name: SENTINEL_ISSUER
              value: "https://idx-stage.linkhealth.com/auth/realms/developer-platform"

            # ---------------------------------------------------------------
            # Oracle EPS datasource
            # ---------------------------------------------------------------
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: oracle-credentials
                  key: oracle-eps-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oracle-credentials
                  key: oracle-eps-password


            # ---------------------------------------------------------------
            # SSL keystore password
            # ---------------------------------------------------------------
            - name: server-ssl-keyStorePassword
              valueFrom:
                secretKeyRef:
                  name: {{ include "ars-service-svc.fullname" . }}
                  key: server-ssl-keyStorePassword

          ports:
            - name: http
              containerPort: {{ .Values.arsServiceSvc.service.port }}
              protocol: TCP

          # ---------------------------------------------------------------
          # PROBES (HTTPS – matches server.ssl.enabled=true)
          # ---------------------------------------------------------------
          livenessProbe:
            httpGet:
              path: /ars/actuator/health/liveness
              port: http
              scheme: HTTPS
            initialDelaySeconds: 120
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              path: /ars/actuator/health/readiness
              port: http
              scheme: HTTPS
            initialDelaySeconds: 120
            timeoutSeconds: 5

          # ---------------------------------------------------------------
          # VOLUME MOUNTS
          # ---------------------------------------------------------------
          volumeMounts:
            - name: truststore
              mountPath: /tls/truststore.jks
              subPath: truststore.jks
              readOnly: true

            - name: keystore
              mountPath: /tls/keystore.p12
              subPath: keystore.p12
              readOnly: true

            - name: ars-service-svc-secret-store
              mountPath: /mnt/ars-service-svc-secret-store
              readOnly: true

            - name: app-config
              mountPath: /config/application.properties
              subPath: application.properties
              readOnly: true

          resources:
            {{- toYaml .Values.arsServiceSvc.resources | nindent 12 }}

      # ------------------------------------------------------------------
      # VOLUMES
      # ------------------------------------------------------------------
      volumes:
        - name: keystore
          secret:
            secretName: ars-service-svc-keystore
            items:
              - key: keystore.p12
                path: keystore.p12

        - name: truststore
          secret:
            secretName: ars-service-svc-keystore
            items:
              - key: truststore.jks
                path: truststore.jks

        - name: ars-service-svc-secret-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: ars-service-svc-secretproviderclass

        - name: app-config
          configMap:
            name: {{ include "ars-service-svc.fullname" . }}
            items:
              - key: application.properties
                path: application.properties
{{- end }}
